Added Routes structure
CodeBreakersGCEK/taucord pull request #9
Opened 2024-05-11 17:37 UTC by Airbornharsh

- added routes

![Screenshot from 2024-05-11 23-02-49](https://github.com/CodeBreakersGCEK/taucord/assets/95279849/51746930-791f-4b0c-956d-79d40355ec7f)

closes: issue #8

2024-05-11 18:02 UTC, zephyrus21 requested changes

2024-05-11 18:02 UTC, zephyrus21 commented on src/components/Channels.tsx
> +    return;
use `return () => {};` instead of `return;`

for reference [click here](https://blog.logrocket.com/understanding-react-useeffect-cleanup-function)

2024-05-11 18:02 UTC, zephyrus21 commented on src/components/Channels.tsx
> +        ))}
Same

> Let's separate this logic into a func, make the return cleaner, do all the programmatic stuff outside the return.

2024-05-11 18:02 UTC, zephyrus21 commented on src/components/Members.tsx
> +      })}
Same

> Let's separate this logic into a func, make the return cleaner, do all the programmatic stuff outside the return.

2024-05-11 18:02 UTC, zephyrus21 commented on src/components/Servers.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
use `return () => {};` here for useEffect cleanup

2024-05-12 17:30 UTC, zephyrus21 commented on src/components/Channels.tsx
> +    };
keep this function outside useEffect

2024-05-12 17:30 UTC, zephyrus21 commented on src/components/Servers.tsx
> +    }
same

> keep this function outside useEffect

2024-05-12 17:30 UTC, zephyrus21 commented on src-tauri/src/main.rs
> +mod helpers;
Why do we need this?

2024-05-12 17:32 UTC, Airbornharsh commented on src/components/Servers.tsx
> +    }
Okay

2024-05-12 17:32 UTC, Airbornharsh commented on src-tauri/src/main.rs
> +mod helpers;
to get the channels and server details

2024-05-12 17:35 UTC, Airbornharsh commented on src/components/Channels.tsx
> +    };
Done

2024-05-12 17:39 UTC, zephyrus21 commented on src-tauri/src/main.rs
> +mod helpers;
yeah but do we need `mod helpers;`

2024-05-13 07:28 UTC, zephyrus21 approved these changes

2024-05-13 07:29 UTC, merged